// Auto-generated by scripts/fix_everything.js
// Do not edit manually, redeploy & re-run the script instead.

export const TOKEN_ADDRESS = "0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F";
export const KYC_ADDRESS = "0xb9A219631Aed55eBC3D998f17C3840B7eC39C0cc";
export const MARKETPLACE_ADDRESS = "0x4D2D24899c0B115a1fce8637FCa610Fe02f1909e";

// Admin address used in AdminDashboard UI (not on-chain enforced)
export const ADMIN_ADDRESS = "0xf17f52151ebef6c7334fad080c5704d77216b732";
